#!/bin/bash
set -euo pipefail

# Documentation hints:
#
# https://medium.com/google-developers/how-to-generate-fabulous-api-reference-docs-for-ios-5bd297b9697d
# https://medium.com/google-developers/how-to-migrate-ios-api-reference-from-doxygen-to-jazzy-35bd89c6a92b
# https://pandoc.org
# https://kapeli.com/docsets

function current_script_fullpath() {
    local scriptfile
    if (( $BASH_SUBSHELL > 1 ))
    then
        echo ">>> Error: function '$FUNCNAME' can't be invoked in a sub-shell." 1>&2
        kill -9 -- $$
        exit 1
    fi
    scriptfile="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    scriptfile="${scriptfile}"/$(basename "$0")
    echo "$scriptfile"
}

source_path="$(current_script_fullpath)"
cd "$(dirname "$source_path")"

mkdir Temp
ditto Branch Temp/Branch
ditto Branch.xcodeproj Temp
ditto LICENSE Temp
ditto README.md Temp
cd Temp

jazzy \
    --clean \
    --objc \
    --umbrella-header Branch/Branch.h \
    --framework-root . \
    --module Branch \
    --sdk macosx \
    --author Branch \
    --author_url https://branch.io \
    --module-version 1.0 \
    --copyright "Copyright © 2018 Branch. All rights reserved." \
    --use-safe-filenames \
    --exclude=Branch/BNCLog.h,Branch/BranchMainClass+Private.h \
    --output ../Documentation \
    --github_url "https://github.com/BranchMetrics/Branch-SDK-Mac" \
    --github-file-prefix  "https://github.com/BranchMetrics/Branch-SDK-Mac/tree/v0.87.1" \
#     --docset-icon FILEPATH
#     --docset-path DIRPATH
#     --skip-documentation

cd ..
ln -vsf Documentation/index.html Documentation.html

cp Examples/TestBed-Mac/TestBed-Mac/Assets.xcassets/Branch.imageset/Branch-16.png \
   Documentation/icon.png

cp Examples/TestBed-Mac/TestBed-Mac/Assets.xcassets/Branch.imageset/Branch-16.png \
   Documentation/docsets/Branch.docset/icon.png

cp Examples/TestBed-Mac/TestBed-Mac/Assets.xcassets/Branch.imageset/Branch-32.png \
   Documentation/icon@2x.png

cp Examples/TestBed-Mac/TestBed-Mac/Assets.xcassets/Branch.imageset/Branch-32.png \
   Documentation/docsets/Branch.docset/icon@2x.png

rm -Rf Temp
