# Uncomment the next line to define a global platform for your project
# platform :osx, '10.14'

target 'SaaS_SDK_TestBed_MacOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BranchMacOS', :path => './../'
end
 
