#!/bin/bash
set -euo pipefail

# git-tag-release  -  Commit and push the current git changes.  Create a version tag and push to master.
#
# Edward Smith, January 2017

function full_path_of_directory() {
    local directory_name
    directory_name="$1"
    current_directory=$(pwd)
    while [[ "$(basename "$current_directory")" != "$directory_name" && ${#current_directory} -gt 1 ]]
    do
        current_directory=$(dirname "$current_directory")
    done
    if (( ${#current_directory} <= 1 ))
    then
        echo ">>> Error: Path of '$1' not found." 1>&2
        kill -9 -- $$
        exit 1
    fi
    echo "$current_directory"
}

project_directory="$(full_path_of_directory mac-branch-deep-linking)"
cd "$project_directory"

version=$(defaults read "$project_directory"/Branch/Info.plist CFBundleShortVersionString)
version=${version}-beta
git_branch=$(git symbolic-ref --short HEAD)

echo ">>> Pushing version $version to '$git_branch'..." 1>&2

git add --all
git commit --allow-empty -m "Release ${version}."
git tag "${version}"
git push --tags origin "$git_branch"
