#!/bin/bash
set -euo pipefail

# Documentation hints:
#
# https://medium.com/google-developers/how-to-generate-fabulous-api-reference-docs-for-ios-5bd297b9697d
# https://medium.com/google-developers/how-to-migrate-ios-api-reference-from-doxygen-to-jazzy-35bd89c6a92b
# https://pandoc.org
# https://kapeli.com/docsets

function full_path_of_directory() {
    local directory_name
    directory_name="$1"
    current_directory=$(pwd)
    while [[ "$(basename "$current_directory")" != "$directory_name" && ${#current_directory} -gt 1 ]]
    do
        current_directory=$(dirname "$current_directory")
    done
    if (( ${#current_directory} <= 1 ))
    then
        echo ">>> Error: Path of '$1' not found." 1>&2
        kill -9 -- $$
        exit 1
    fi
    echo "$current_directory"
}

project_directory="$(full_path_of_directory mac-branch-deep-linking)"
cd "$project_directory"

mkdir Temp
ditto Branch Temp/Branch
ditto Branch.xcodeproj Temp
ditto LICENSE Temp
ditto README.md Temp
ditto CHANGELOG.md Temp
cd Temp

jazzy \
    --clean \
    --objc \
    --umbrella-header Branch/Branch.h \
    --framework-root . \
    --module Branch \
    --sdk macosx \
    --author Branch \
    --author_url https://branch.io \
    --module-version 1.0.0 \
    --copyright "Copyright © 2018 Branch. All rights reserved." \
    --use-safe-filenames \
    --exclude=Branch/BNCLog.h,Branch/BranchMainClass+Private.h,Branch/BranchCommerce.h \
    --output ../Documentation/HTMLDocumentation \
    --github_url "https://github.com/BranchMetrics/Branch-SDK-Mac" \
    --github-file-prefix  "https://github.com/BranchMetrics/Branch-SDK-Mac/tree/v1.0.0" \
    --head "<link rel=\"icon\" href=\"icon.png\">" \
    --docset-icon ../Documentation/Images/Branch-16.png \
    --docset-path ../Branch.docset

#     --podspec FILEPATH \
#     --skip-documentation

cd "$project_directory"
ln -vsf Documentation/HTMLDocumentation/index.html Documentation.html

cp Documentation/Images/Branch-16.png \
   Documentation/HTMLDocumentation/icon.png

cp Documentation/Images/Branch-16.png \
   Documentation/Branch.docset/icon.png

cp Documentation/Images/Branch-32.png \
   Documentation/HTMLDocumentation/icon@2x.png

cp Documentation/Images/Branch-32.png \
   Documentation/Branch.docset/icon@2x.png

ditto Documentation/Images \
    Documentation/HTMLDocumentation/Documentation/Images

ditto Documentation/Images \
    Documentation/Branch.docset/Contents/Resources/Documents/Documentation/Images

rm Documentation/Branch.tgz
rm -Rf Temp
